### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by burtbeckwith**

### CODE REVIEW

**Comment by zoumra** [comment]
Hi Burt,

Thanks for the cleanup & approval..
But then, i still can't see the "opencmis" plugin on grails web site. 
Thanks to let me know.

Kind regards,

## 

Ludovik

**Comment by burtbeckwith** [comment]
When you do the first release the plugin page will get created. Run "grails publish-plugin --stacktrace" to do the release

**Comment by zoumra** [comment]
Done, It works now. I suppose there is a filter for "-SNAPSHOTé suffixed versions... Thanks.

## 

Ludovik

**Comment by burtbeckwith** [comment]
Yes, the plugin page isn't updated or created if SNAPSHOT appears in the version

**Pull request merged**
